//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngelissimaTest {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Data() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AngelissimaTest.Data", typeof(Data).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to [{&quot;quantity&quot;:8,&quot;id&quot;:1,&quot;registrationdate&quot;:&quot;2017-03-06T01:48:00.639&quot;,&quot;productid&quot;:1},
        ///{&quot;quantity&quot;:3,&quot;id&quot;:2,&quot;registrationdate&quot;:&quot;2017-03-06T01:48:16.378&quot;,&quot;productid&quot;:2},
        ///{&quot;quantity&quot;:6,&quot;id&quot;:3,&quot;registrationdate&quot;:&quot;2017-03-06T01:48:26.821&quot;,&quot;productid&quot;:3},
        ///{&quot;quantity&quot;:3,&quot;id&quot;:4,&quot;registrationdate&quot;:&quot;2017-03-06T01:48:33.635&quot;,&quot;productid&quot;:4},
        ///{&quot;quantity&quot;:3,&quot;id&quot;:5,&quot;registrationdate&quot;:&quot;2017-03-07T05:00:00&quot;,&quot;productid&quot;:1},
        ///{&quot;quantity&quot;:2,&quot;id&quot;:6,&quot;registrationdate&quot;:&quot;2017-03-10T05:00:00&quot;,&quot;productid&quot;:2}].
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [{&quot;description&quot;:&quot;Product 1&quot;,&quot;saleprice&quot;:2500,&quot;minimunquantity&quot;:1,&quot;barcodes&quot;:{&quot;barcode&quot;:&quot;1234&quot;},&quot;unitprice&quot;:2000,&quot;id&quot;:1,&quot;name&quot;:&quot;Product 1&quot;},{&quot;description&quot;:&quot;Product 2&quot;,&quot;saleprice&quot;:3000,&quot;minimunquantity&quot;:1,&quot;barcodes&quot;:{&quot;barcode&quot;:&quot;2345&quot;},&quot;unitprice&quot;:3500,&quot;id&quot;:2,&quot;name&quot;:&quot;Product 2&quot;},{&quot;description&quot;:&quot;Product 3&quot;,&quot;saleprice&quot;:8000,&quot;minimunquantity&quot;:1,&quot;barcodes&quot;:{&quot;barcode&quot;:&quot;3456&quot;},&quot;unitprice&quot;:11000,&quot;id&quot;:3,&quot;name&quot;:&quot;Product 3&quot;},{&quot;description&quot;:&quot;Product 4&quot;,&quot;saleprice&quot;:5500,&quot;minimunquantity&quot;:1,&quot;barcodes&quot;:{&quot;barcode&quot;:&quot;4567&quot;},&quot;u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
    }
}
